### PR TITLE
fixing problems with fitting registration page to smaller screens

### PR DESCRIPTION
**Pull request by matusturjak**
Now registration page dynamically fit to users screen. #345

### CODE REVIEW

**Review by CholujMartin — COMMENTED** [review]
obrázok
Can you resize buttons too or atleast center them
obrázok

**Comment by matusturjak** [comment]
> obrázok
> Can you resize buttons too or atleast center them
> obrázok

center buttons 'Prihlasenie' and 'Registracia' when screen is too small

issua

**Review by reibek — COMMENTED** [review]
This looks and feels much better. I think, it's correct solution.

**Review by reibek — APPROVED** [review]

**Comment by BranislavTvrdy** [comment]
I'm still getting shifted carousel on initial load with this solution.
Snímka obrazovky 2020-11-10 001246

**Pull request merged**
