### PR TITLE
#595 reset button

### PR DESCRIPTION
**Pull request by Flacore**
reset button for student timetable to remove all changes made to it

### CODE REVIEW

**Review by marektavac — COMMENTED** [review]
These are just the changes for GUI, it has to be approved by somebody else...

**Comment by PeterKulas** [comment]
After click on my name is timetable reseted, but menu with buttons to change id, reset timetable or change to dark mode is not displayed. Does anyone have the same problem?

**Comment by Rado996** [comment]
When i click on my name on top of the page menu is diplayed but only for a second and whole website reloades. It will reset time table and reload page right after menu is shown, so i can not click on any button in menu.

**Comment by Flacore** [comment]
Ok, i will try just push new timetable without reloading the website so we would see if it help

**Comment by Rado996** [comment]
Problem is it will reload the site for me after clicking on my name, not
the reset button.

Dňa st 9. 11. 2022, 11:23 Michal Molitoris ***@***.***>
napísal(a):

**Comment by Flacore** [comment]
i finally find what it was missing and right now its in fully working state, when doing review please check it if i forgot some use case

**Review by PeterKulas — APPROVED** [review]
Everything works fine.

**Pull request merged**
