### PR TITLE
Lectures can be removed and edited as intended. Also changed min max … (#372)

### PR DESCRIPTION
**Pull request by CholujMartin**
Lectures can be removed and edited as intended. Also changed min max length of block

### CODE REVIEW

**Review by marektavac — COMMENTED** [review]
This changes are for frontend developers.. I'm not experiences with this code.. But for backend changes, I will be glad to review your it...

**Comment by CholujMartin** [comment]
> 
> 
> This changes are for frontend developers.. I'm not experiences with this code.. But for backend changes, I will be glad to review your it...

Ok, I just wanted to add you as review for additional change(changed min max in block) if it is ok with you mostly

**Comment by marektavac** [comment]
I don't know the reason so hard to say...

**Review by BranislavTvrdy — APPROVED** [review]
Seems good to me. I don't mind the change in min/max length of block, since it's only a boundary of arrows inside of the input box, and greater value can be typed inside.

**Pull request merged**
