### PR TITLE
465 ldap

### LINKED ISSUE #465: LDAP_login_doesn't_work_on_AWS
After I try to login using LDAP, 1-2 minute nothing happens and then blank page appears.

### PR DESCRIPTION
**Pull request by CholujMartin**
Closes #465

### CODE REVIEW

**Comment by CholujMartin** [comment]
Only thing is taht when using localhost it is needed to turn SecureSocketLayer to false and port on 389

**Comment by CholujMartin** [comment]
Wasn't a lot of coding but was heavy on research and testing also thanks to @brano98 for help with this

**Comment by brano98** [comment]
I approve this, only one small change was required.

**Comment by CholujMartin** [comment]
Then approve please so I can merge.

**Comment by brano98** [comment]
@CholujMartin I cannot approve it, because I made change. Maybe try to send review request again?

**Review by brano98 — APPROVED** [review]

**Pull request merged**
