### PR TITLE
594 api call for subject time table is not working

### PR DESCRIPTION
**Pull request by Rado996**
Fix for course time table api call, added host name of ldap to logs for better identification of errors.

### CODE REVIEW

**Comment by Rado996** [comment]
Hello, could you guys test this branch on your devices if you can? With docker and without it. Right now there is some problem on develop branch after i pushed merge for subject shortcuts and i can not replicate that issue to investigate it. Please check your logs when you start application and look for any errors, mainly for " |ERROR|WebAPI.Startup|Exception during creating DB seed : A timeout occurred after 30000ms selecting a server using CompositeServerSelector" error. If you experience any errors please let me know, this branch should fix course time table api call so you should be able to add other subjects or see time table of your subjects when you enable them in menu on left side.

**Comment by PeterKulas** [comment]
I checked it without docker and i didnt get your error. Timetable of my subjects didnt work.

**Review by MichalMurin — COMMENTED** [review]
After refreshing database for my account, I successfuly tested new features.

#### When running without Docker: 
 - Application shows correct course shortcuts and I am able to add course (if I choose correct course, application automaticly fill teachers name and room). Course switches on the left panel are working correctly.

#### When running with Docker: 
- Everything decsribed above works exactly the same, except course shortcuts. Application running on Docker does not show Course shortcuts and shows only course code.

**I did not recieve described ERROR in any case.**

**Comment by Rado996** [comment]
I pushed fix for courses, there were some duplicits. With @MichalMurin  we found out that you have to clean old Courses from your Database and import new ones, also change last time your student time table was updated so it will update it. Then just refresh your page. Please pull new changes and check tutorial i created on how to change data in your database, you will find in our teams under Files->MongoDB

**Comment by MichalMurin** [comment]
> I pushed fix for courses, there were some duplicits. With @MichalMurin we found out that you have to clean old Courses from your Database and import new ones, also change last time your student time table was updated so it will update it. Then just refresh your page. Please pull new changes and check tutorial i created on how to change data in your database, you will find in our teams under Files->MongoDB

- [TUTORIAL](https://zilinskauniverzita.sharepoint.com/:w:/s/edu-fri-swapify/EYxasfswsdhDkYcb-sv4mZoB2JWYSi4WeZ6Bb48c-qxX8Q?e=hBakAZ)
- [NEW DATA](https://zilinskauniverzita.sharepoint.com/:u:/s/edu-fri-swapify/EYBPd4FeqZBEv6TWMagHSesBQesrpFxW-lWtiRngNf4Y_w?e=FJvFhA)

**Review by fri-team — APPROVED** [review]
Looks OK

**Pull request merged**
