### PR TITLE
609 model update for teachers account implementation

### PR DESCRIPTION
**Pull request by MichalMurin**
I refactored whole code, to be less specific about type of user (student, teacher). 
The main change is that entity "Student", is now called "TimetableData", because it stores all the information connected to the user's timetable. All code connected to it should be now correctly renamed.  New enum is added for timetable type (StudentTimetable, TeacherTimetable, Unknown).

Then I successfuly  implemented teacher interface, so teacher should be now able to log in and displays his timetable, he should not see change requests on the left panel, and he should be able to show or hide blocked hours in timetable. Teacher is not able to request course change.

To test this, you will have to change your database too:

1. Download [MongoDbCompass](https://www.mongodb.com/try/download/compass)
2. Run swapify on localhost
3. Connect to database in MongoDbCompass - Docker: **mongodb://localhost:27018**, Old way: **mongodb://localhost:27017**      (recomended old way, because in docker are not shown changes made in frontend)
4. On left panel, click on Swapify
5. Click on users -> Drop collection
6. Click on + next to 'Swapify' -> create collection
7. Name it 'users'
8. Drop collection 'Student'
9. Create collection -> name it 'TimetableData'
10. Rerun swapify app -> app will fill the database, so it can take some time

- You can now test new features, you can use teacher personal nymber (99195), or use testing accout (teacher@swapify.com, password: Heslo123)

### CODE REVIEW

**Comment by SimonAlfons71830** [comment]
Everything works fine. I would just suggest to edit some things:
To disable or hide function to edit "Blokované" blocks and add teacher's name or hide the icon.
edit1
edit1
And the second suggestion is to hide or remove function to add a subject. 
edit2
edit2

**Comment by MichalMurin** [comment]
> Everything works fine. I would just suggest to edit some things: To disable or hide function to edit "Blokované" blocks and add teacher's name or hide the icon. edit1 And the second suggestion is to hide or remove function to add a subject. edit2



Every suggestion is successfuly implemented + I removed icon from blocked hours.

**Comment by SimonAlfons71830** [comment]
Login works fine, but when I tried to register or login with email it did not work and answer was 400 - bad request.
image

**Review by SimonAlfons71830 — APPROVED** [review]
The functionality works good. I tested it with changing my personal number to teachers and also I logged in with the email you gave us. I tested some functions in new teachers interface and it was all successful. You changed the things I recommended so I approve this pull request! :)

**Pull request merged**
