### PR TITLE
#364 aws ip address change

### PR DESCRIPTION
**Pull request by MarekZorvan**
AWS IPv4 was changed so we had to change the addess in our server settings.

### CODE REVIEW

**Review by BranislavTvrdy — APPROVED** [review]
Did note read. You said it was good.

**Comment by marektavac** [comment]
@MarekZorvan nepresli asi testy... Treba to pozriet, ale hlavne podla zmien v kode to nevyzera, ze by tie zmeny suviseli so zmenou IP... Takto by sa asi nemalo commitovat... Ci som zle nieco pochopil?

**Review by BranislavTvrdy — CHANGES_REQUESTED** [review]
if (existingUser != null && !existingUser.EmailConfirmed) in UserController.cs

**Comment by BranislavTvrdy** [comment]
We fixed the mergingg problem in another branch, this pull request is obsolete.

**Pull request closed without merging**
