### PR TITLE
317_autodeploy

### PR DESCRIPTION
**Pull request by brano98**

### CODE REVIEW

**Comment by CholujMartin** [comment]
Is it right to do autodeploy in develop shouldn't we create new branch like release 1.0 and use actions there ? I think this develop branch should go into the test machine that Ondrej said can be obtained. And release should be on the actual machine.

**Comment by brano98** [comment]
We discussed today that it will autodeploy in develop until new branch is created. Then required changes will be made.

**Comment by marektavac** [comment]
@CholujMartin , you should prepare the strategy for deployment, but we miss it still. But we want to use it ASAP.. It is hard to test functionalities without immediate deployment. It should not be so complicated to reconfigure it later

**Comment by marektavac** [comment]
Sorry, @CholujMartin it should be prepared by @Malwaare

**Review by marektavac — APPROVED** [review]
Is there some explanation for the yml content? It would be good to do some while you remember it...
If I understand good you build everything from scratch...
Is not it already builded after commit or merge?
Or this is replacement for that?
As you can see it would be real good to have some general documentation about the logic - what is it, how does it work in general (for some new members of the team) and than some detail explanation to the commands in the yml (e.g. code comments)

I approve the merge, but this documentation would be really perfect (github wiki?)

**Comment by marektavac** [comment]
By the way, very good job, not so much code, but I'm sure a lot's of study and experiments

**Pull request merged**
