### PR TITLE
API student timetable #64

### PR DESCRIPTION
**Pull request by davidm1766**
API for
- add new block 
- remove existing block

### CODE REVIEW

**Comment by davidm1766** [comment]
@marektavac I removed ID from blocks

**Comment by marektavac** [comment]
@davidm1766 You have removed logical id from block, but id is still inside Block entity...

**Comment by davidm1766** [comment]
> @davidm1766 You have removed logical id from block, but id is still inside Block entity...

yes it is because block is inherited from BaseEntity which has ID - should I remove inheritance?

**Comment by davidm1766** [comment]
> @davidm1766 You have removed logical id from block, but id is still inside Block entity...

Yes bacause Block is inherited from BaseEntity which has ID, should I remove inheritance? 

I will fix it in branch #68 after merge

**Comment by marektavac** [comment]
Discuss with others if we will need the id in the block, if no, you must remove it from entity totally. Otherwise somebody sooner or later will use it and it will be mistake.

**Pull request merged**
