### PR TITLE
#640 login page redesign

### PR DESCRIPTION
**Pull request by PeterKulas**

### CODE REVIEW

**Comment by SimonAlfons71830** [comment]
Great redesign! Just add some text here or remove text "Treti text" so it's not appearing there. 
image
Also I can't log in and this error shows up. Can anyone confirm if that's only my issue? 
image

**Comment by MichalMurin** [comment]
> Great redesign! Just add some text here or remove text "Treti text" so it's not appearing there.
> image
> Also I can't log in and this error shows up. Can anyone confirm if that's only my issue?
> image

I noticed the same issue, and I have already discussed it with @PeterKulas. He confirmed to me, he will check it and try to resolve it.

**Comment by PeterKulas** [comment]
I'll check it out today or tomorrow. About the "treti text", do you have any suggestion what should i display there?

**Comment by SimonAlfons71830** [comment]
> I'll check it out today or tomorrow. About the "treti text", do you have any suggestion what should i display there?

I would do something like this but if anyone has something other in mind feel free to edit it. 
Pridajte podnadpis
@PatrikCader27

**Comment by SimonAlfons71830** [comment]
Login works fine, but when I tried to register or use email as login I've got response as bad request.
image

**Comment by PeterKulas** [comment]
image
Bad request issue doesnt work on develop also so we should make new issue for that. I didnt broke registration with this pull request.

**Review by MichalMurin — APPROVED** [review]
Everything looks good, third carousel should be edited in the future.

**Comment by PeterKulas** [comment]
> Everything looks good, third carousel should be edited in the future.

I will edit it when i ll get specific info.

**Pull request merged**
